apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgresql-pv
  namespace: postgresql-ns
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/tank/database
    server: 10.0.3.5
