apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgresql-pvc
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
