apiVersion: v1
kind: Service
metadata:
  name: vllm-inference-server
  namespace: vllm-ns
spec:
  selector:
    app: vllm-inference-server
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: http
