apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: open-webui-ns
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: open-webui
