apiVersion: v1
kind: Service
metadata:
  name: tautulli-service
  namespace: tautulli-ns
spec:
  selector:
    app: tautulli
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8181
  type: LoadBalancer
