apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: tautulli-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-chown
        image: alpine
        command: [ "sh", "-c", "chown -R 1000:1000 /mnt/data" ]
        volumeMounts:
        - name: tautulli-data
          mountPath: "/mnt/data"
      containers:
      - name: tautulli
        image: ghcr.io/tautulli/tautulli
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        ports:
        - containerPort: 8181
        volumeMounts:
        - name: tautulli-data
          mountPath: "/config"
      volumes:
      - name: tautulli-data
        persistentVolumeClaim:
          claimName: tautulli-pvc
