apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: general-api-image-update-automation 
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@clortox.com
      messageTemplate: 'Update image tag to {{range .Updated.Images}}{{println .}}{{end}}'
  update:
    path: ./api/general-api
    strategy: Setters

