apiVersion: v1
kind: Service
metadata:
  name: games-service
  namespace: games-ns
spec:
  selector:
    app: games
  ports:
    - name: factorio
      protocol: UDP
      port: 34197
      targetPort: 34197
    - name: factorio-tui
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: minecraft
      port: 25565
      targetPort: 25565
    - name: minecraft-rcon
      port: 28016
      targetPort: 28016
  type: LoadBalancer
