apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql-system
spec:
  interval: 5m
  chart:
    spec:
      chart: postgreql-ha
      version: "11.9.8"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: postgresql
  valuesFrom:
  - kind: ConfigMap
    name: postgresql-values-map
    valuesKey: values.yaml
