kind: pipeline
name: default

steps:
  - name: notify
    image: clortox/drone-ntfy
    settings:
      URL: https://ntfy.clortox.com
      USERNAME: drone
      PASSWORD:
        from_secret: ntfy_password
      TOPIC: drone-builds
      MESSAGE: Flux configuration updated! Check if out.
      CLICK: https://git.clortox.com/Infrastructure/Gluttony-Cluster/
      TITLE: Gluttony-Cluster
      PRIROITY: High
