apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pvc
  namespace: games-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 16Gi
