apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: games-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      #initContainers:
      #- name: modpack-downloader
      #  image: alpine:latest
      #  volumeMounts:
      #  - name: minecraft-modpacks
      #    mountPath: /modpacks
      #  env:
      #  - name: MODPACK_URL
      #    value: "https://s3.clortox.com/minecraft-modpacks/modpack-latest.zip"
      #  command: ["/bin/sh"]
      #  args:
      #  - "-c"
      #  - |
      #    rm -rf /modpacks/*
      #    wget -O /modpacks/modpack.zip "$MODPACK_URL"
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java8-jdk
        env:
        - name: EULA
          value: "TRUE"
        - name: ENABLE_RCON
          value: "TRUE"
        - name: RCON_PORT
          value: "28016"
        - name: MEMORY
          value: "8G"
        - name: USE_AIKAR_FLAGS
          value: "false"
        - name: ENABLE_ROLLING_LOGS
          value: "false"
        - name: TZ
          value: "America/New_York"

        - name: VERSION
          value: "1.12.2"
        - name: MODPACK
          value: "https://s3.clortox.com/minecraft-modpacks/modpack-latest.zip"
        - name: REMOVE_OLD_MODS
          value: "TRUE"
        - name: TYPE
          value: "FORGE"
        - name: CUSTOM_SERVER_PROPERTIES
          value: |
            level-type=EarthCubic
            level-name=big-world
            view-distance=16
            vertical-view-distance=-1

        - name: ICON
          value: "https://s3.clortox.com/minecraft-modpacks/server-icon.png"
        - name: OVERRIDE_ICON
          value: "TRUE"
        - name: MOTD
          value: "Lol. Lmao Even."
        - name: MAX_PLAYERS
          value: "50"
        - name: SPAWN_PROTECTION
          value: "0"
        - name: DIFFICULTY
          value: "hard"
        - name: OPS
          value: "Gritos_Internos"
        - name: ALLOW_FLIGHT
          value: "TRUE"
        ports:
        - containerPort: 25565
        - containerPort: 28016
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
        - name: minecraft-modpacks
          mountPath: /modpacks
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-pvc
      - name: minecraft-modpacks
        emptyDir: {}
