apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-ai-models-pvc
  namespace: local-ai-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 80Gi
