apiVersion: v1
kind: Service
metadata:
  name: text-generation-webui-service
  namespace: text-gen-ns
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 7860
      targetPort: 7860
    - name: api
      port: 5000
      targetPort: 5000
    - name: stream
      port: 5005
      targetPort: 5005
  selector:
    app: text-generation-webui
