apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-gen-pvc
  namespace: text-gen-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
