apiVersion: v1
kind: Pod
metadata:
  name: cuda-test
  namespace: default
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:11.0.3-base-ubuntu20.04
    command: ["while true; sleep 1000; done"]
    resources:
      limits:
        nvidia.com/gpu: 1
