apiVersion: v1
kind: Pod
metadata:
  name: cuda-test
  namespace: default
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:10.0-base
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1
