apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-api
  namespace: api-ns
  labels:
    app: general-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-apps
  template:
    metadata:
      labels:
        app: api-apps
    spec:
      containers:
      - name: general-api
        image: git.clortox.com/tyler/general-api:latest
        env:
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: general-api-secret
              value: access-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: general-api-secret
              value: secret-key
        - name: CONFIG
          value: "/config.yaml"
        ports:
        - containerPort: 8000
      volumes:
      - name: config-volume
        configMap:
          name: general-api-config-map
          items:
          - key: config.yaml
            path: config.yaml


