apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-claim
  namespace: plex-ns
spec:
  encryptedData:
    PLEXCLAIM: AgBRORdxkfM6/Xned+rg+sKOlPUpWdKpe8q7gjRM2kUbNgSxcnhC4BmRZG4Z2TPRkWZlrroRFIlNplwzAWrjSYID6Hu+Xcmzd26pHzOLUx+TEC02leZRhxDI9GdKodYP0yS1GpLcuIQ65XzgxWdhS7cRRK02Y901UYLbAQF4HQkzC3FBchi9tk8F+7XEAetUpYRhfNScrSjh7/cX0Zbo6D8OQmY+TOODhxTvSf5C41cZ0gZp5Y5tIWTbqG6q5PJW6nywPVkJHRCJDWafaVuOP8h+Srg+x0qBAdKsIYSnBzYCkx+dxFDkw7DBlAmmj015TAmWwNPQml3e5RURmIK0uOWOdjveYywPuTlo5vNPGSI1c3BU4wvi+RY7pct/ytW9VBx1fLI/C7+/tPbw5B5CSafdOTtB4RBu9nvaz/urd1QHPGSVS1CLZoew56+9vus0I7024hUJmYa0cpM7y2LLxKDeOOn+KT+dtWovP9HRkcdP+GwTIQ2SfI3GCO2lin9Z3Km7DTAiKdovDET51CCgvxs8zZKUd/ZrYGQVyppvYp+efjSXgtMe3tjdTqMUe9jpz7GOeI6WbGXK7sOZ+mvhKynonjxxto53gLl6M/wHcz0GU4bY22J7R/BzToopPdXYNo6tzWHl9EK8kIhWbf3cmaGd5jczwH9ZetCXW55P/n/HBqFI5O0d4sQPpOtZ83OqtQ8YyAQmG37qTwvuzpmw/hIXx0a1o6Cr+f+cfA==
  template:
    metadata:
      creationTimestamp: null
      name: plex-claim
      namespace: plex-ns
---
