apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-config
  namespace: plex-ns
spec:
  storageClassName: local-storage
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Main/Container-Configs/Plex/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gluttony
