apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-media
  namespace: plex-ns
spec:
  volumeName: plex-pv-media
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 18000Gi
