apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-claim
  namespace: plex-ns
spec:
  encryptedData:
    PLEXCLAIM: AgC/cTzyXB/9Yge89ya4PYf21VIKfBLAeQMceE51C+e5p90Vqr57wkiGOs4MHBomfAXf8tRjDPSMkCqBhEwMeH1vpWp0M8YUmW1pAgJ1jTMRJeyAR2aVTjanim8cBLAxsofif+V/9DGxUa6M0P2V6ld2fBvw7qIdO4UC/YFv6pGTRgCWp9H61Rh934RtFdiBuSa2booYFDa86tJA5r1cWBN6YLJW+ri716juKobcy3dMaS2kQDKMVv1Bs4Rq5EKgxXbLJjrHgTTulkB2WxcQFftsckM5aMI9rmstNiBhTzrSYM9RYaEaYw/uEcBYZGnjfxL2IxhxZp9Cr7qyUnlVR8jnXAZobR88nMsImuc8B4qWyWwaBFnYEBLM7MBDlN+1wsdjEhGltAfjc1s7wHsWDleZKAC1rl2FLc4MELP1FbJ3nNM+3cYqqaP9fbFWZ//0P6ttzB/U8Q7GFl6qWkQQpZfb6FSfz3D4j1BxCtAu0ct0kHxDxdfqWW8xqLE/zFNLR6edYkSTc7YPCD22X5yydmGBaB3WLyolUpDZHIQXRb9a4/UM3Pi9rh+Y6BnDenlfha/G3cHJdOrLfavCqM5P2/pLey6BIUY38oKePU9OJ+f0x3xPORkTGZLYJuB2HfjAliuYkrasLlX9KAPNJ/AarjXO0bMFkksTiKEvmU3yOG+lghiA01MZn4kbz8rk9dzH3Fdt1FJaopQ0rmRkgec7Sc74ZfUQL30OHzXHjQ==
  template:
    metadata:
      creationTimestamp: null
      name: plex-claim
      namespace: plex-ns
---
