apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-media
spec:
  storageClassName: local-storage
  capacity:
    storage: 18000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Main/Media"
  nodeAffinity:
    required:
      ndeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gluttony
