apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-claim
  namespace: plex-ns
spec:
  encryptedData:
    PLEX_CLAIM: AgBKYZur5cfL/WOGEs6sciEoqE4Jf5+nNVXTzLYni7bGkifPed7b4PTPK0+Mdao3Z6AkGceYnNlYMOUoEJBjC+5aEWf1+enJHmlbjwqYrRAIyG90nlA79e35dRHd6XcEoxKxshOL9HNQbywXaSdk/FlXSz3y2JbiOxU+x3Tnkl4vJRVBBncL+B2EFpNwF5tK9A7s3pYXvrVSPYJuk5yUH8USyu9EOUrS3wzqggq5Y2zTXEngtXRl42qPHWHFtYqeE+2wlutPKvcqtnoIxVr88910NFvv4+h1PSrJztEPgUiStE4APpehZlF8X0UpGK4kF0ozsDHY0NJoJpa8rK69vYfj/y1EX9RBs5s076lfwHtpItaKxQ4+a/dnk0vs2qLj4AEG57iKrPbnTicreYTCFyeSUKwTKUTXc+8PALWnu8sk4JAR1c0lQhLnPbHzX/yURlYzMGTlCue03hllS4r7ZknOatW7HjAQveqn6j0s893Ntbo6vAr8Ooe1EjevSED1cA7OUaQnYLge7zQjzlL928raWhu44ltRQG0xswyQpbphBJCIcGqxEq/yVozTKb5X+J7Jir1xmE4x9NG/PAkUVtlrNhM7yjfF/2xZITyqNlAHJlU3UfQg4yI18DB6RdgvzLCXEqhvg6brtjQyhRtg4PowVvB3nCZPSH9Qjn2u1aeeSqEypCyQRe77X7awc5hLkAQRjyO+I1N5Z/S/x1FTabZfhR0n7/MYHbQTsA==
  template:
    metadata:
      creationTimestamp: null
      name: plex-claim
      namespace: plex-ns
---
