apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-config
  namespace: plex-ns
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
