apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-bundle
  namespace: plex-ns
  annotations:
    force-recreate: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeSelector:
        kubernetes.io/hostname: gluttony
      containers:
      - name: plex
        image: plexinc/pms-docker:public
        env:
        - name: TZ
          value: EST
        - name: PLEX_UID
          value: "1000"
        - name: PLEX_GID
          value: "1000"
        ports:
        - containerPort: 32400
        - containerPort: 8234
        - containerPort: 32469
        - containerPort: 1900
        - containerPort: 32410
        - containerPort: 32412
        - containerPort: 32413
        - containerPort: 32414
        volumeMounts:
        - name: plex-config
          mountPath: /config
        - name: plex-media
          mountPath: /data

        # Sidecar providing access to upload/view/download raw media files
      - name: filebrowswer
        image: git.clortox.com/infrastructure/filebrowser:v1.0.1
        env:
        - name: ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: filebrowser-secret
              key: ADMIN-PASS
        - name: DEFAULT_USERNAME
          value: "default"
        - name: DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: filebrowser-secret
              key: DEFAULT-PASS
        - name: BRANDING_NAME
          value: "Media Storage"
        - name: AUTH_METHOD
          value: "json"
        - name: AUTH_HEADER
          value: "X-My-Header"
        - name: PERM_ADMIN
          value: "false"
        - name: PERM_EXECUTE
          value: "false"
        - name: PERM_CREATE
          value: "true"
        - name: PERM_RENAME
          value: "true"
        - name: PERM_MODIFY
          value: "true"
        - name: PERM_DELETE
          value: "false"
        - name: PERM_SHARE
          value: "true"
        - name: PERM_DOWNLOAD
          value: "true"
        volumeMounts:
        - name: plex-media
          mountPath: /srv
        ports:
        - containerPort: 80

      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-pvc-config
      - name: plex-media
        persistentVolumeClaim:
          claimName: plex-pvc-media
