apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plex-ns
spec:
  selector:
    app: plex
  type: LoadBalancer
  ports:
  - name: plex
    protocol: TCP
    port: 32400
    targetPort: 32400
  - name: filebrowswer
    protocol: TCP
    port: 8080
    targetPort: 8080
