apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-config
  namespace: plex-ns
spec:
  volumeName: plex-pv-config
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 18000Gi
