apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: torrent-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torrenter-apps
  template:
    metadata:
      labels:
        app: torrenter-apps
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - gluttony
      containers:
      - name: deluge
        image: lscr.io/linuxserver/deluge:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: DELUGE_LOGLEVEL
          value: "error"
        ports:
        - containerPort: 8112
        - containerPort: 6881
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: downloads-volume
          mountPath: /downloads
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: deluge-config-pvc
      - name: downloads-volume
        persistentVolumeClaim:
          claimName: blackhole-pvc

