apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-full-access-rolebinding
  namespace: sealed-secrets
subjects:
- kind: ServiceAccount
  name: sealed-secrets
  namespace: sealed-secrets
roleRef:
  kind: ClusterRole
  name: secret-full-access-role
  apiGroup: rbac.authorization.k8s.io
