apiVersion: apps/v1
kind: Deployment
metadata:
  name: big-agi-deployment
  namespace: big-agi-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: big-agi
  template:
    metadata:
      labels:
        app: big-agi
    spec:
      containers:
        - name: big-agi-container
          image: ghcr.io/enricoros/big-agi
          ports:
            - containerPort: 3000
