apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-pvc-media
  namespace: navidrome-ns
spec:
  volumeName: plex-pv-media
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 18000Gi
