apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana-ns
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  type: LoadBalancer
