apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmfakecloud-pvc-data
  namespace: rmfakecloud-ns
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
