apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik-ns
spec:
  encryptedData:
    postgres-password: AgA6U69famrB8AmiRsZLZg9oS6gj7oVZMm4yhnrUe5evOEWdXsoDkNmo7yea8UYrAJUeHp6fe6w2/qbObKWfvGIZhT4DVEi8QqTbLlEywRg1cOUssSI8I3hb4IMXCGgv75Jf9SKLy3zYoYMaDy7Kb3Z4EIqumvLnOMivhyO9G5kN/A31/4N5A8dGJmEnjupgiaT/sc++G1kaDN4mkNDd9EdmbZyc3B3xXqinQp5ZmxU0Yk0mgCbW35BbkseqQaDY7NFk354VvbE6Gxdo4O5IVkX5jTejVD84v7vFm7zpYLwJd15yDTzy8lf2pGin/H5SBk5zskT56RxNEo5ML3wvH9kOJqA7RpZPP0p4Wc7BOcF3o10zRJxa/saVxnQTcjueOG0PgXDlmYAqhOZm3a8BqqMbnvk9VNEM7zXc63vX7N0zoCC74TJ2rfUBQxuxP+fma3/DlH/s6JdNhO5qx+qNARrsocsq/io6codE1aB/iKKu1NKyBCiTFKA0DbCvUuae/wHSEZjOYE2+tYWNVonvdrwuU1+fx34G8vWFWfc4wGMASWlokLQtPxZYcEA0bVsTAfGOrnnZQp4bcVgs6Y2fUDxydFnyOvMoGGvpG8xiQHkVQ+NeCsEj2Q8ry9VtA3utO9NS5Kz5sDAhnFU7wZXN0bVptXSVTktazXNTVpg0HGAgcTYPo0wJ7F9q6aXEb8/WF6lQ6uxMTUHD38SD8gj3qQvJmdyLFQ9ya8FJ79SYb+EzCA==
    secret-key: AgBQ3SA7X/flQ3F4zqGPubLXUMUwYs4rW+qld86zBjzMaX2g0t3VNWRMhaVDYS3IfpVVboIWIEAQwkErb4mGi4YuVSPa1DgVFyxUh//CXg01IkSUqqoW1OEtpFwjKb+VCqRiW5I5ZPwvSHSOxy7Yh7feH5y7clqj3fiqObeEl+EUZpbwmdT1vJsefMBejnUMxCy1ZjU/87TvG9+zOT5rcxFefxd3AuRhJ2H+od9HkJ7ZFHvW4Ywdicb9kAhHlGBWTZIAkYgH0KJLytyC0M7AXt1pzuaQqSXIsgpmYUek2h8wE7vgiitVWtd9MiF4e6XhMtHKcfch5eVC4uIkZcLmbw1ChAxefiuU/74W+iRpsIjQ9JYebM6zaFCw94JReDSf9RlbtyQG1wscbL0AH2QozupFZhRxT80tUArope3fplohSqxJHckYWeODv8f2VaCQIb1nBJoXg30E0EPjXaZM8jMjbv/ZrCWtP9ia8+s3+0Mj3KelKvVXwWIpW4JwiEdwi3H8SEr9SVuqgNkbFGz9zz6PqtOQ797iL8EKv4C+qSqXQCe6FuiMXX+zgE/+MqtyuTGqjXS9hLH/lEmKSAaWsEVDdy/1JD/bitw4Cwo3glhKxc8Pgd/DBTRoZ0L6CQW+d/Y9G3Dw+3qFfu2AjFoTlyNl4j8XgRDW2bL9nMI0ET8z7QqiKBVr+H47Yuof/mGa2a8FJH358l8uTVRsX25SGv5+FEQZzNVzGsdId0/GjMgIibp6kHJdAPyLxP40d5e7HayKVQ==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik-ns
---
