apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-config-pvc
  namespace: homarr-ns
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
