apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
      - name: immich-machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:release
        env:
        - name: UPLOAD_LOCATION
          value: /usr/src/app/upload
        - name: DB_HOSTNAME
          value: postgresql.postgresql-system.svc.cluster.local
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: password
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: database
        - name: REDIS_HOSTNAME
          value: redis-master.redis-system.svc.cluster.local
        volumeMounts:
        - name: model-cache
          mountPath: /cache
      volumes:
      - name: model-cache
        emptyDir: {}
