apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-microservices
  namespace: immich-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-microservices
  template:
    metadata:
      labels:
        app: immich-microservices
    spec:
      containers:
      - name: immich-microservices
        image: ghcr.io/immich-app/immich-server:release
        args: ["start.sh", "microservices"]
        env:
        - name: UPLOAD_LOCATION
          value: /usr/src/app/upload
        - name: DB_VECTOR_EXTENSION
          value: pgvector
        - name: DB_HOSTNAME
          value: postgresql.postgresql-system.svc.cluster.local
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: password
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: database
        - name: REDIS_HOSTNAME
          value: redis-master.redis-system.svc.cluster.local
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-immich-secret
              value: REDIS_PASS
        volumeMounts:
        - name: upload-volume
          mountPath: /usr/src/app/upload
      volumes:
      - name: upload-volume
        persistentVolumeClaim:
          claimName: immich-library-pvc
