apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-consume-pvc
  namespace: paperless-ngx-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
