apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-export-pvc
  namespace: paperless-ngx-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
