apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx-service
  namespace: paperless-ngx-ns
spec:
  selector:
    app: paperless-ngx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
