apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackhole-pvc
  namespace: torrent-ns
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi

