apiVersion: v1
kind: PersistentVolume
metadata:
  name: blackhole-pv
  namespace: torrent-ns
spec:
  storageClassName: local-storage
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /Main/Black Hole
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gluttony

