apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: torrent-ns
spec:
  volumeName: media-pv
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 18000Gi
