apiVersion: v1
kind: Service
metadata:
  name: torrenter-service
  namespace: torrent-ns
spec:
  type: LoadBalancer
  ports:
  - port: 9696
    targetPort: 9696

  - port: 8112
    targetPort: 8112
  - port: 6881 
    targetPort: 6881

  selector:
    app: torrenter-apps 

