apiVersion: v1
kind: Service
metadata:
  name: torrenter-service
  namespace: torrent-ns
spec:
  type: LoadBalancer
  ports:
  - name: prowlarr
    port: 9696
    targetPort: 9696

  - name: deluge-ui
    port: 8112
    targetPort: 8112
  - name: deluge-p2p
    port: 6881
    targetPort: 6881
  - name: radarr
    port: 7878
    targetPort: 7878

  selector:
    app: torrenter-apps
