apiVersion: apps/v1
kind: Deployment
metadata:
  name: memerr
  namespace: memerr-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memerr
  template:
    metadata:
      labels:
        app: memerr
    spec:
      containers:
      - name: memerr
        image: git.clortox.com/infrastructure/memerr:1.0.65
        imagePullPolicy: Always
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: memerr-secret
              key: DISCORD_TOKEN
        - name: S3_URL
          value: "s3.clortox.com"
        - name: S3_UN
          valueFrom:
            secretKeyRef:
              name: memerr-secret
              key: S3_UN
        - name: S3_PW
          valueFrom:
            secretKeyRef:
              name: memerr-secret
              key: S3_PW
        - name: S3_TLS
          value: "True"
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: memerr-secret
              key: S3_BUCKET
