apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr 
  namespace: torrent-ns
  labels:
    app: radarr 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torrenter-apps 
  template:
    metadata:
      labels:
        app: torrenter-apps
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - gluttony
      initContainers:
      - name: volume-permission
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumes:
          - mountPath: /config
            name: radarr-config
      containers:
      - name: radarr 
        image: lscr.io/linuxserver/radarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: radarr-config 
          mountPath: /config
        - name: downloads-volume
          mountPath: /downloads
        - name: movies-storage
          mountPath: /movies
          subPath: movies/movies_normal
      volumes:
      - name: radarr-config 
        persistentVolumeClaim:
          claimName: radarr-config-pvc
      - name: downloads-volume
        persistentVolumeClaim:
          claimName: blackhole-pvc
      - name: movies-storage
        persistentVolumeClaim:
          claimName: media-pvc

