apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: torrent-ns
spec:
  type: ClusterIP 
  ports:
  - name: radarr
    port: 7878
    targetPort: 7878

  selector:
    app: torrenter-apps 

