apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: torrent-ns
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torrenter-apps 
  template:
    metadata:
      labels:
        app: torrenter-apps
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: prowlarr-data
          mountPath: /config
      volumes:
      - name: prowlarr-data
        persistentVolumeClaim:
          claimName: prowlarr-pvc

