apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fission
  namespace: fission-ns
spec:
  chart:
    spec:
      chart: fission-all
      sourceRef:
        kind: HelmRepository
        name: fission
        namespace: flux-system
  interval: 5m
  values:
    serviceType: LoadBalancer
    namespace: fission
    repository: fission/fission
    tag: 1.19.0
    pullPolicy: IfNotPresent

