apiVersion: v1
kind: Service
metadata:
  name: node-red-service
  namespace: node-red-ns
spec:
  selector:
    app: node-red
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1880
  type: LoadBalancer
