apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red 
  namespace: node-red-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red 
  template:
    metadata:
      labels:
        app: node-red 
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: freshrss
        image: nodered/node-red
        ports:
        - containerPort: 1880
        volumeMounts:
        - name: node-red-data
          mountPath: /data
        - name: settings-file
          mountPath: /data/settings.js
          subPath: settings.js
      volumes:
      - name: node-red-data 
        persistentVolumeClaim:
          claimName: node-red-pvc
      - name: settings-file
        configMap:
          name: nodered-settings

