apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red 
  namespace: node-red-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red 
  template:
    metadata:
      labels:
        app: node-red 
    spec:
      containers:
      - name: freshrss
        image: nodered/node-red
        ports:
        - containerPort: 1880
        volumeMounts:
        - name: node-red-data
          mountPath: /data
      volumes:
      - name: node-red-data 
        persistentVolumeClaim:
          claimName: node-red-pvc

