apiVersion: v1
kind: Service
metadata:
  name: local-ai
  namespace: local-ai-ns
spec:
  selector:
    app: local-ai
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
