apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai
  namespace: localai-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localai
  template:
    metadata:
      labels:
        app: localai
    spec:
      runtimeClassName: nvidia
      containers:
      - name: localai
        image: quay.io/go-skynet/local-ai:latest-aio-gpu-nvidia-cuda-12
        ports:
        - containerPort: 80
          #env:
        resources:
          limits:
            nvidia.com/gpu: 3
        volumeMounts:
        - mountPath: "/models"
          name: models
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: localai-pvc
