apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio 
  namespace: games-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games 
  template:
    metadata:
      labels:
        app: games 
    spec:
      containers:
      - name: factorio 
        image: factoriotools/factorio:stable
        ports:
        - containerPort: 34179
        - containerPort: 27015
        volumeMounts:
        - name: factorio-save
          mountPath: /factorio
      volumes:
      - name: factorio-save
        persistentVolumeClaim:
          claimName: factorio-pvc

