apiVersion: v1
kind: Service
metadata:
  name: factorio-service
  namespace: games-ns
spec:
  selector:
    app: games 
  ports:
    - name: factorio
      protocol: UDP
      port: 34197
      targetPort: 34197
    - name: factorio-tui
      protocol: TCP
      port: 27015
      targetPort: 27015
  type: LoadBalancer

