apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: ollama-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      runtimeClassName: nvidia
      containers:
      - name: ollama
        image: ollama/ollama
        env:
        - name: OLLAMA_HOST
          value: 0.0.0.0
        - name: OLLAMA_MODELS
          value: "/models"
        ports:
        - containerPort: 11434
        resources:
          limits:
            nvidia.com/gpu: 2
        volumeMounts:
        - name: ollama-volume
          mountPath: "/my-models"
      volumes:
      - name: ollama-volume
        persistentVolumeClaim:
          claimName: ollama-pvc
