apiVersion: v1
kind: Service
metadata:
  name: freshrss-service
  namespace: freshrss-ns
spec:
  selector:
    app: freshrss
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

