apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      volumes:
      - name: data-mount
        persistentVolumClaim:
          claimName: uptime-kuma-pvc
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma
        ports:
          - containerPort: 3001
        volumeMounts:
          - mountPath: '/app/data'
            name: data-mount

