apiVersion: v1
kind: Service
metadata:
  name: catagorize-ai-service
  namespace: firefly-ns
spec:
  selector:
    app: firefly-iii
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

