apiVersion: apps/v1
kind: Deployment
metadata:
  name: catagorize-ai
  namespace: firefly-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly-iii
  template:
    metadata:
      labels:
        app: firefly-iii
    spec:
      containers:
      - name: catagorize-ai
        image: ghcr.io/bahuma20/firefly-iii-ai-categorize
        ports:
        - containerPort: 3000
        env:
        - name: FIREFLY_URL
          value: https://money.clortox.com
        - name: ENABLE_UI
          value: true
        - name: FIREFLY_PERSONAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: firefly-iii-ai
              key: FIREFLY_PERSONAL_TOKEN
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: firefly-iii-ai
              key: OPENAI



