apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: firefly-iii-secret
  namespace: firefly-ns
spec:
  encryptedData:
    APP_PASSWORD: AgA7BLMdU+G86r0DBHiG5L1MO2o2CvItkxuAb6UOIM1p4LRkJ9w8lENdTO3TCJtftnyC9mXs0tCyJs3jjiAP/4p2SKuIA+ldXQrenihSm/jmtAgxl9kRnKWvKrbtsaKiIcCUd0Ty1a8EC9/o1tb9r0iTyRvdr7W//zV53ulg5N+Gt4EKmsyWDHK6gJYnjviV4uTpkjhE1p2IYB41LIOO0LRiLMMmW4esItHyeOWDvkfm9nQFjnMSgIzCiO51T9UJZeG+/InuDcDk9ARe7pQrm7/3yK/tDmyug4jMjvX71OEBEoSxMbVNmfrqsOlJoeqfZ5DDYo3jvxf3+xBH+OseGxzPyaAiUvgtqLQHoeEYPTV/8NVItID/WI0ljBJzNzSmxCEPQmarrCVfzpZJ9AsCouskMagDNuPKj7BCE6FbsmmYZOCJF7bmrTZxmqDeSuFj47tf7B2UFHkMB/NTaATSF4aOl1wKaTwWoC1QmEUArav0GJ71n/AvKEra6K2T9hvTnB2oQU0zZSUHmVUQPspmwCVIPwsgoUUx4h1b7ljDYOOv0fNCsRD6GXsb0reIqGo4g+5KtwrElHcSPnqnyRE5AFnSZ9Ra4VYCfSD0rj8yqT+5Y8v7OouJXWmEVue8J1Z7A8x3JUiaqvAn1R90JKvuAjUm7QuMkLlUYGwL1CHFo0DYEV/r+rHo9Rs0qcfRiFvm9H9yjt8FOq3ymyEy9RxpBnsGEWWwNNdcX3mINOnCXnckbg==
    DB_PASSWORD: AgADYYlULTe7/wlRasSKw0RdcV90wcaDe1c0oPz72nO11rIniWUv6221wnSmINJoos49NccJKxx5SQ+fN46KijOLMXETdOmlme/5zHfGFP4YoarMB2EF6LhnzEy2Fc/nS5dlBj78duj1eWCw6cLaKqmUtKJaH8waphJP7FL0B3I4XjeDFN0pbehxAkLZHqXfbuH9JFrgHJ86uY4EB9YrPTmxQQj0WEU6oxGu4POsefy1JVOvvOWlBgZVaCjCzE9YplW8JsVajYITKAm1S97O4pcGL2OPtPnS7pDW6eRN+Bf28f1umKKWEmxWup5o+TSORFcc2KPUBczvKB6Z5hL9SSLZKlXkuMB9u0UemdJRo7K0gLZ6pSbx7P04D8qBq0bTXC/wTclSUoR6nJXWJM5NRlzP8I50isn1bV6yM0p6iS9/IACNJBfkjIgNjvauz3+erQsESMsc/dguGWV+P1JQItljyG/lq7P1G+n8Xb9+fUaFnSyXx7xzENlA7uNgFX7OJilYUBDGmr0EecBAT3CIdHBBgG7+/lj9JYxxB5N/5j7EmMycAG3hSpKQnwDNIq3bVff9KBKHtgtfnfyfrTsSyDr6WE+H+fjCp7245ml/3TJSFYhj5VyRtz3b0t/rfFAwlSFNj982QWSi5Bm7f1T9Mu1kWgY8TU/keL6nVYB3XtuzPpiNjaSXWJSsIcE87fuY56FQB1IpJp/MedYo7szlAStjxcGHjYUscjySveWMuwCAkQ==
  template:
    metadata:
      creationTimestamp: null
      name: firefly-iii-secret
      namespace: firefly-ns
---
