apiVersion: v1
kind: Service
metadata:
  name: activepieces-service
  namespace: activepieces-ns
spec:
  selector:
    app: activepieces
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
