apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api-ns
spec:
  type: LoadBalancer
  ports:
  - name: general-api
    port: 8080
    targetPort: 80

  selector:
    app: api-apps
